### ISSUE TITLE
More permissive usage of semicolon

### ISSUE THREAD

**Issue by sergey-goncharov** [arcalab/lince#1]
I suggest relaxing the parser rules for using the semicolon. Ideally, it should be allowed everywhere between atomic commands, arbitrary many times. This should enable examples 

1. ``v:=0; v'=1 for 2; v'=3 for 2;``
2. ``v:=0; v'=1 for 2; ; v'=3 for 2``

**Comment by joseproenca** [comment]
I agree with the suggestion. The semicolon was used only as a separator of statements, but most imperative languages use it as the end of an atomic statement. We adapted the grammar to require the semicolon at the end of every atomic statement, to be more familiar to most programmers.
